### PR TITLE
fix: IllegalStateException

### LINKED ISSUE #62: fail to do gitlab merge request  decoration on absence of new_coverage metric
**Describe the bug**
the pull request analysis for gitlab is succefully created, while the pr decoration failed, with trace back as follows appearing in ce.log:

```
020.01.10 04:08:22 ERROR ce[AW-No1gDpsRBuIhDvm6H][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Execution of task class com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask failed
java.lang.IllegalStateException: There is no value when status is NO_VALUE
	at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at org.sonar.ce.task.projectanalysis.api.posttask.ConditionImpl.getValue(ConditionImpl.java:163)
	at java.base/java.util.Optional.map(Unknown Source)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.AnalysisDetails.createAnalysisSummary(AnalysisDetails.java:109)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.gitlab.GitlabServerPullRequestDecorator.decorateQualityGateStatus(GitlabServerPullRequestDecorator.java:160)
	at com.github.mc1arke.sonarqube.plugin.ce.pullrequest.PullRequestPostAnalysisTask.finished(PullRequestPostAnalysisTask.java:126)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.executeTask(PostProjectAnalysisTasksExecutor.java:113)
	at org.sonar.ce.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:107)
	at org.sonar.ce.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:91)
	at org.sonar.ce.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:63)
	at org.sonar.ce.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.executeTask(CeWorkerImpl.java:209)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$ExecuteTask.run(CeWorkerImpl.java:191)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:158)
	at org.sonar.ce.taskprocessor.CeWorkerImpl$TrackRunningState.get(CeWorkerImpl.java:133)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:85)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:53)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Software Versions**
 - SonarQube Version:  Version 7.9.2 (build 30863)
 - Plugin Version: custom build from master at commit 9a12d6d57e6fd

### PR DESCRIPTION
**Pull request by jizhilong**
fix #62

### CODE REVIEW

File: src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java [hunk 1]
```diff
@@ -106,13 +107,16 @@ public String getCommitSha() {
...
+                findQualityGateCondition(CoreMetrics.NEW_COVERAGE_KEY)
+                    .filter(condition -> condition.getStatus() != EvaluationStatus.NO_VALUE)
+                    .map(QualityGate.Condition::getValue)
+                    .map(BigDecimal::new).orElse(null);
 
         double coverage = findMeasure(CoreMetrics.COVERAGE_KEY).map(MeasureWrapper::getDoubleValue).orElse(0D);
 
         BigDecimal newDuplications = findQualityGateCondition(CoreMetrics.NEW_DUPLICATED_LINES_DENSITY_KEY)
-                .map(QualityGate.Condition::getValue).map(BigDecimal::new).orElse(null);
+            .filter(condition -> condition.getStatus() != EvaluationStatus.NO_VALUE)
```
Comment (tisoft) [inline src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java]: Since this is basically the same code as above, I think it would be nice if it would be in the same code format

Comment (jizhilong) [reply src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java]: sure, I'd reformat these fragments.

**Comment by mc1arke** [comment]
Thanks for the contribution.
