### PR TITLE
Gitlab PR Decorator Fixes for Sonar 8.1

### LINKED ISSUE #84: Wrong Gitlab API url for MR decoration
Hello. First of all, thanks for a good job.

I've compiled jar from here:

https://github.com/mc1arke/sonarqube-community-branch-plugin/tree/sq-8_1-support

and when it comes publishing MR comment, plugin fails to do that. I'm seeing following in console:

GET /api/v4/api/v4/projects/root%2Fsonarqube/merge_requests/13/commits

As I see plugin gets hostURL with /api/v4, but also adds its own /api/v4 to url

### LINKED ISSUE #85: Gitlab PR decoration throws exception when no new_coverage condition is provided
**Describe the bug**
When in Sonar conditions there is no new_coverage condition (and i doubt that this condition is necessary) the plugin throws Exception. `IllegalStateException("Could not find New Coverage Condition in analysis")`.  I guess it's kinda related to #62 but the reason of the issue lies here https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/1e28de64c8d608db5bdc1bd020dcfa073b9e0e89/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java#L153-L155

The easiest solution would be 

```
String coverageValue = analysis.findQualityGateCondition(CoreMetrics.NEW_COVERAGE_KEY)
                            .filter(condition -> condition.getStatus() != QualityGate.EvaluationStatus.NO_VALUE)
                            .map(QualityGate.Condition::getValue)
                            .orElse("0");
```

it's kinda duplicates the code from here https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/1e28de64c8d608db5bdc1bd020dcfa073b9e0e89/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java#L115-L120

So may be we can put some duplicated lines into separate method from `AnalysisDetails.java`. I unfortunately have no idea how to implement fix nicely

**Expected behavior**
The plugin should not throw an exception. May be only log some info.

**Screenshots**

**Software Versions**
 - SonarQube Version:  Version 7.9.2
 - Plugin Version:  custom build from master at commit 1e28de64c8d608db5bdc1bd020dcfa073b9e0e89]

### LINKED ISSUE #86: GitLab comments in files - non-obvious parameter requirement
**Bug summary**
If you enable the com.github.mc1arke.sonarqube.plugin.branch.pullrequest.file.comment.enabled = parameter, but leave the com.github.mc1arke.sonarqube.plugin.branch.pullrequest.delete.comments.enabled ( default = False), the server will not comment on the source code. This is true because if the server comments on the source code for each analysis, the comments will repeat the same problems (if they have not been resolved), but this is not obvious to the end user. When the user turns on the com.github.mc1arke.sonarqube.plugin.branch.pullrequest.file.comment.enabled = parameter True, the com.github.mc1arke.sonarqube.plugin.branch.pullrequest.delete.comments.enabled parameter should turn on automatically.

**To Reproduce**
1. In the project settings, enable the "Enable file comment" option using the GitLab provider:
screenshot
2. In the project settings, configure the section according to your server.
3. Run the pullrequest Analysis
4. SonarQube don't create threads in source code in GitLab.

**Expected behavior**
SonarQube server creates threads in source code in GitLab

**Software Versions**
 - SonarQube Version: 7.9.2
 - Plugin Version: last commit in master branch

### PR DESCRIPTION
**Pull request by tisoft**
* Support automatic configuration in GitLab CI
* Align property names with sonar developer edition
* Autodelete comments
* Don't fail if no new coverage condition is provided
* Support multiple pipelines on one commit

Fixes #84
Fixes #85
Fixes #86
Closes #74

### CODE REVIEW

**Comment by tisoft** [comment]
@mc1arke Could you take a look?

With those changes Gitlab MR decoration is running fine for me on SonarQube 8.1.

Implementing properly resolving of discussions instead of just deleting the comments is on my list, but I don't know when I will get to it yet.

File: src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java [hunk 1]
```diff
@@ -67,10 +71,14 @@
 
 public class GitlabServerPullRequestDecorator implements PullRequestBuildStatusDecorator {
 
-    public static final String PULLREQUEST_GITLAB_URL =
-            "com.github.mc1arke.sonarqube.plugin.branch.pullrequest.gitlab.url";
-    public static final String PULLREQUEST_GITLAB_REPOSITORY_SLUG =
-            "com.github.mc1arke.sonarqube.plugin.branch.pullrequest.gitlab.repositorySlug";
+    public static final String PULLREQUEST_GITLAB_INSTANCE_URL =
+            "sonar.pullrequest.gitlab.instanceUrl";
```
Comment (mc1arke) [inline src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java]: Since I don't think these properties are available in Sonarqube developer edition, could you prefix them with `com.github,mc1arke....` (or confirm that are available in Sonarqube developer edition)

Comment (tisoft) [reply src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java]: They are used by Sonarqube developer edition, but currently only internally, if the build is done in gitlab ci. They don't support other environments yet for MR decoration. https://jira.sonarsource.com/browse/MMF-1901 will fix that, and the parameters will probably get documented as soon as that is implemented.

**Comment by renanperalta** [comment]
@tisoft and @mc1arke I using  plugin 1.2.1 Snapshot. Can you provide the last version of 1.2.1, with this fix?  For me test and feedback here.

**Comment by dcherniv** [comment]
@renanperalta try building from source. It's fairly straightforward.
```
git clone https://github.com/mc1arke/sonarqube-community-branch-plugin.git
git checkout sq-8_1-support
./gradlew clean build
```
The jar would be located in build/libs/
I would imagine that snapshot generation is not something that's easy to do with every single commit.
